pydjango_ci_integration/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from tasks import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('tasks.urls'))
]

handler404 = views.Custom404.as_view()
handler500 = views.Custom500.as_view()

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskList.as_view(), name='tasks_list'),
    path('new/', views.TaskCreate.as_view(), name='tasks_new'),
    path('task/<int:pk>', views.TaskDetails.as_view(), name='tasks_view'),
    path('edit/<int:pk>', views.TaskUpdate.as_view(), name='tasks_edit'),
    path('delete/<int:pk>', views.TaskDelete.as_view(), name='tasks_delete'),
]

tasks/models.py
"""
    Task model
"""
from django.db import models
from django.urls import reverse


class Task(models.Model):
    """
    Stores a single Task entry
    """
    task_title = models.CharField(max_length=50, verbose_name='Task Title')
    task_description = models.TextField(max_length=200, verbose_name='Task Description')
    task_created = models.DateTimeField(auto_now_add=True)
    task_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        :return: string to represent Task model
        """
        return self.task_title

    def get_absolute_url(self):
        """
        :return: returns the absolute url for task model
        """
        return reverse('tasks:tasks_edit', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

tasks/views.py
"""
Task app: Views file
"""
from django.views.generic import ListView, TemplateView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from tasks.models import Task


class TaskList(ListView):
    """
    Task list Generic List View
    """
    model = Task
    ordering = ['-task_created']

    def get_context_data(self, **kwargs):
        context = super(TaskList, self).get_context_data(**kwargs)
        context.update({'nlink': 'list'})
        return context


class TaskCreate(CreateView):
    """
    Task list Generic Create View
    """
    model = Task
    fields = ['task_title', 'task_description']
    success_url = reverse_lazy('tasks:tasks_list')

    def get_context_data(self, **kwargs):
        context = super(TaskCreate, self).get_context_data(**kwargs)
        context.update({'nlink': 'new'})
        return context


class TaskDetails(DetailView):
    """
    Task list Detail View
    """
    model = Task
    fields = ['task_title', 'task_description', 'task_created', 'task_updated']


class TaskUpdate(UpdateView):
    """
    Task list Update View
    """
    model = Task
    fields = ['task_title', 'task_description']
    success_url = reverse_lazy('tasks:tasks_list')

    def get_context_data(self, **kwargs):
        context = super(TaskUpdate, self).get_context_data(**kwargs)
        context.update({'nlink': 'update'})
        return context


class TaskDelete(DeleteView):
    """
    Task list Delete View
    """
    model = Task
    success_url = reverse_lazy('tasks:tasks_list')


class Custom404(TemplateView):
    """
    Task list Custom 404 View
    """
    template_name = 'tasks/404.html'


class Custom500(TemplateView):
    """
    Task list Custom 500 View
    """
    template_name = 'tasks/500.html'

tasks/templates/tasks/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="short">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    {% if title %}
    <title>Semaphore CI: Python / Django Example - {{title}}</title>
    {% else %}
    <title>Semaphore CI: Python / Django Example</title>
    {% endif %}
    <style type="text/css" rel="stylesheet">
        .card {
            float: left;
            margin: 10px;
        }
        .error-template {padding: 40px 15px;text-align: center;}
        .error-actions {margin-top:15px;margin-bottom:15px;}
        .error-actions .btn { margin-right:10px; }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'tasks:tasks_list' %}">Tasks</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link {% if nlink == 'list' %}active{% endif %}" href="{% url 'tasks:tasks_list' %}">All Tasks</a>
            <a class="nav-item nav-link {% if nlink == 'new' or nlink == 'update' %}active{% endif %}" href="{% url 'tasks:tasks_new' %}">Create New Task</a>
        </div>
    </div>
</nav>
<div class="container-fluid">
    {% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/tasks/task_confirm_delete.html
{% extends 'tasks/base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?<br>
        <button type="submit" class="btn btn-primary">Delete Task</button>
    </form>
{% endblock content %}

tasks/templates/tasks/task_detail.html
{% extends 'tasks/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            Details of {{ object.task_title }}
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ object.task_description }}</p>
                <footer class="blockquote-footer">Created at: {{ object.task_created }} <cite title="Source Title">Updated at: {{ object.task_updated }}</cite></footer>
            </blockquote>
            <a href="{% url 'tasks:tasks_list' %}" class="fa-link icons-back-link"><span class="glyphicon glyphicon-home"></span>
                Go back to Task List page </a>
        </div>
    </div>
{% endblock content %}

tasks/templates/tasks/task_form.html
{% extends "tasks/base.html" %}

{% block content %}
{% if nlink == 'update' %}
    <h4>Update New Task</h4>
{% else %}
    <h4>Create New Task</h4>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
        {% if field.errors %}
            <div class="form-group error">
                <label class="label-info">{{ field.label }}</label>
                <div class="field-box">{{ field }}
                    <span class="help-block">
                        {% for error in  field.errors %}{{ error }}{% endfor %}
                    </span>
                </div>
            </div>
        {% else %}
        <div class="form-group">
            <label class="label-info">{{ field.label }}</label>
            <div class="field-box">{{ field }}
                {% if field.help_text %}
                <p class="help-block"><small>{{ field.help_text }}</small></p>
                {% endif %}
            </div>
        </div>
        {% endif %}
    {% endfor %}
    {% if nlink == 'update' %}
        <button type="submit" class="btn btn-primary">Update Task</button>
    {% else %}
        <button type="submit" class="btn btn-primary">Create Task</button>
    {% endif %}
</form>

{% endblock content %}

tasks/templates/tasks/task_list.html
{% extends 'tasks/base.html' %}

{% block content %}
  {% if object_list %}
    <h4>All tasks</h4>
    {% for task in object_list %}
      <div class="card" style="width: 25rem;">
        <div class="card-body">
          <h5 class="card-title">{{ task.task_title }}</h5>
          <p class="card-text">{{ task.task_description }}</p>
          <a href="{% url 'tasks:tasks_view' task.id %}" class="card-link">View Task</a>
          <a href="{% url 'tasks:tasks_edit' task.id %}" class="card-link">Update Task</a>
          <a href="{% url 'tasks:tasks_delete' task.id %}" class="card-link">Delete Task</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <div class="row">
      <div class="col-md-12">
        <div class="error-template">
          <h1>
            Got Lucky!</h1>
          <h2>
            No tasks Found</h2>
          <div class="error-actions">
            <a href="{% url 'tasks:tasks_new' %}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
              Create new task </a>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content%}
